### PR TITLE
README: Remove unrestricted permission mention

### PR DESCRIPTION
**Pull request by Siosm**

### CODE REVIEW

**Comment by tsdgeos** [comment]
What's the rationale for not mentioning those 2? I don't understand what you mean with "unrestricted" permission

**Comment by Siosm** [comment]
This is from the discussion at https://github.com/flathub/flathub/pull/1882#discussion_r503763011: https://github.com/flathub/flathub/wiki/App-Requirements#unrestricted-permissions

**Comment by tsdgeos** [comment]
I may be very thick but sincerely i don't understand what these two sentences mean

"Unrestricted permissions

The following permissions can be freely used:"

Unrestricted by what? who? is this a flatpak policy or somehow flathub has created their own policy on top of restrictions? I read those two sentences and i get no understanding of what they mean. Want me to comment that on the ktorrent MR?

**Comment by Siosm** [comment]
> Want me to comment that on the ktorrent MR?

Please do. I'm open to both changes and I'm OK with either version.

**Comment by Siosm** [comment]
I'm guessing this is a split between permissions that are considered safe to grant by default and those that may open a wider access to outside the sandbox.

**Comment by Erick555** [comment]
I think the point is that _Unrestricted permissions_ as listed are essential and doesn't need special explanation in docs and explaining the non obvious ones is sufficient if you want to do that. Also flathub reviewers may not accept app submission if submitter can't explain some broad permissions they add.

**Comment by tsdgeos** [comment]
ok, should we merge this then?

**Pull request merged**
